### ISSUE TITLE
Distortion on pointcloud

### ISSUE THREAD

**Issue by gogojjh** [waymo-research/waymo-open-dataset#14]
Hi, I have one feedback. Please see this figure, [https://s2.ax1x.com/2019/08/26/mWmH2R.png](url), the point clouds are distorted when the vehicle is moving. If such distortion can be fixed, it could be better.
Thanks.

**Comment by tommyjiang** [comment]
The following is the .png file @gogojjh reported. You need to copy the link instead of clicking on it.

![mWmH2R](https://user-images.githubusercontent.com/5961425/63745866-dba31c80-c8d5-11e9-9aed-74c93417d23f.png)

By the way, I would like to know whether meter is the unit of 3D label(x, y, z and length, width, height). Thank you.

**Comment by tommyjiang** [comment]
Thanks for your reply.

**Comment by gogojjh** [comment]
Hi peisun1115,
I think that the distortion may cause biased results on the dataset. For example, when the distortion is large, the ground-truth (bounding box) may not cover all the points of a vehicle. It would be better if the distortion can be fixed as the KITTI did. 
Thanks.

**Comment by gogojjh** [comment]
Hi Pei, 
Sorry for my late response. LiDAR distortion is usually caused by the fast motion of the vehicle. For example, please see the below pictures which I selected two cases from the dataset:
### Case 1: without motion
![000000](https://user-images.githubusercontent.com/11897988/64074047-9ec19600-ccd8-11e9-84d8-5bde26dea860.png)
![Screenshot from 2019-09-01 16-47-31](https://user-images.githubusercontent.com/11897988/64074052-af720c00-ccd8-11e9-8291-2029b7d43527.png)
### Case 2: with fast motion
![000193](https://user-images.githubusercontent.com/11897988/64074053-b1d46600-ccd8-11e9-95c4-2490e319c53e.png)
![Screenshot from 2019-09-01 16-50-21](https://user-images.githubusercontent.com/11897988/64074054-b39e2980-ccd8-11e9-8f2a-a79ac47b69a0.png)
In the **case 2**, you can see that the point clouds of the front and rear LiDAR does not form a regular, circular structure. In other words, such distortion introduces additional noises to the point clouds. making object detection harder. This problem can be solved using pose interpolation.

**Comment by peisun1115** [comment]
Hi gogojjh@:
   Thanks for your explanation on the distortion. I think this is expected as the lidar spins are captured from left to right (clockwise). The lidar spin starts from the middle of the SDC's back. I think it is better to present the user with the raw data. The user is free to run anything algorithm to compensate this effect.

Thanks
Pei

**Comment by peisun1115** [comment]
Hi gogojjh@:
A little more information:

1. The points are not collected at the same instant and the effect is strongly analogous to the rolling shutter effect in image sensors. 

2. You will see similar artifacts on moving objects captured by a stationary car.  The issue is relative motion between sensor and sensed object.

**Comment by gogojjh** [comment]
Hi Pei,
Thanks for your reply. This information is very helpful.  

Thanks,
JIao.

**Comment by xmyqsh** [comment]
@gogojjh
Can you elaborate on how KITTI fixes the distortion caused by the rolling shutter effect in fast movement lidar?

**Comment by ly3106** [comment]
In my view, WOD has effectively addressed the _distortion_ issue. Otherwise, you would notice that the fourth picture displays symmetrical points deployed on the flat ground surface, similar to what the second picture illustrates. I.e., the WOD point cloud more accurately reflects the actual location compared to a perfectly enclosed circle placed on a flat ground surface while the car is in motion. Is my understanding correct? @peisun1115 @gogojjh 



> Hi Pei, Sorry for my late response. LiDAR distortion is usually caused by the fast motion of the vehicle. For example, please see the below pictures which I selected two cases from the dataset:
> 
> ### Case 1: without motion
> ![000000](https://user-images.githubusercontent.com/11897988/64074047-9ec19600-ccd8-11e9-84d8-5bde26dea860.png) ![Screenshot from 2019-09-01 16-47-31](https://user-images.githubusercontent.com/11897988/64074052-af720c00-ccd8-11e9-8291-2029b7d43527.png)
> 
> ### Case 2: with fast motion
> ![000193](https://user-images.githubusercontent.com/11897988/64074053-b1d46600-ccd8-11e9-95c4-2490e319c53e.png) ![Screenshot from 2019-09-01 16-50-21](https://user-images.githubusercontent.com/11897988/64074054-b39e2980-ccd8-11e9-8f2a-a79ac47b69a0.png) In the **case 2**, you can see that the point clouds of the front and rear LiDAR does not form a regular, circular structure. In other words, such distortion introduces additional noises to the point clouds. making object detection harder. This problem can be solved using pose interpolation.

**Comment by reynerliu** [comment]
Hi! I want to know that is there any good method for motion object distortion? I only found a paper-'Lidar with Velocity: Correcting Moving Objects Point Cloud Distortion from Oscillating Scanning Lidars by Fusion with Camera',but it's for the horizon livox lidar and my lidar type is velodyne.
