### ISSUE TITLE
Validation result of all 0's [2D Tracking] 

### ISSUE THREAD

**Issue by Danil328** [waymo-research/waymo-open-dataset#163]
I have finished running our model on validation. However, when submitting to the server, it is giving us a result of all 0's on every metric.
Link - https://waymo.com/open/challenges/entry/?timestamp=1589391350863142&challenge=TRACKING_2D&email=danil28644@gmail.com&submissionType=VALIDATION

**Comment by peisun1115** [comment]
This is because your predictions have too many misses, fps, and mismatches. The sum of them are greater than number of gts which result in negative MOTA.  See [this](https://cvhci.anthropomatik.kit.edu/~stiefel/papers/ECCV2006WorkshopCameraReady.pdf) (sec 2.2) for MOTA def. 

An example of the raw measurement:

      measurements: {   # (car.open_dataset.TrackingMeasurement)  
        num_misses    : 604205  
        num_fps       : 373849  
        num_mismatches: 1159640 
        matching_cost : 166308.26359879971    
        num_matches   : 1197730  
        num_objects_gt: 1801935  
        score_cutoff  : 0.0
      } # tracking_metrics[0].measurements.measurements[0]

**Comment by Danil328** [comment]
Thanks, I found an error with my code.
