### ISSUE TITLE
Heading in camera frame

### ISSUE THREAD

**Issue by bilalsattar** [waymo-research/waymo-open-dataset#209]
Can we transform heading from vehicle frame to camera frame?

**Comment by peisun1115** [comment]
when you say camera frame, i assume it is camera sensor frame instead of image frame.

Yes, you can. Similar as how you transform it from vehicle from to LiDAR sensor frame. But note that such transform assumes all the sensors's frames' x-y planes are in parallel with vehicle frame's x-y plane.  You can check the error by examine the pitch in each sensor's extrinsics.
