### ISSUE TITLE
TensorFlow 2.4 package

### ISSUE THREAD

**Issue by patzm** [waymo-research/waymo-open-dataset#245]
As of today, (2021-02-02), there is no build / package for TensorFlow 2.4. The most recent minor version of TensorFlow that is supported / built is [2.3](https://github.com/waymo-research/waymo-open-dataset/blob/e307878903620af93ad083e47be8412d505d46a6/tf/workspace_tf2_3_0.bzl). Do you have any plans of building a version for 2.4?
How hard would it to contribute that, if you don't have time?
Final question :laughing:, why do you have to maintain separate packages? I couldn't find anything in the readme.

**Comment by peisun1115** [comment]
We need to maintain separate packages because tf upgrades its proto versions in different tf versions. We have to upgrade proto version to be compatible with tensorflow. I recently found this [rename_proto.sh](https://github.com/rockchip-linux/tensorflow/blob/master/tensorflow/contrib/makefile/rename_protobuf.sh) which might help us to avoid this incompatibility. 

it is usually not hard to add a new version unless tensorflow does anything very different in a new version in terms using proto. what is needed  is to add a file like [this](https://github.com/waymo-research/waymo-open-dataset/blob/master/tf/workspace_tf2_3_0.bzl).

Your contribution is welcome.

**Comment by patzm** [comment]
ok cool. Thanks for the quick reply!

**Comment by patzm** [comment]
Done :+1:, can you have a look?
