### ISSUE TITLE
How to build metrics_ops.so?

### ISSUE THREAD

**Issue by lezipg** [waymo-research/waymo-open-dataset#291]
I'm following the tutorial_motion.ipynb and went to issue while import py_metrics_ops.
In waymo_open_dataset/metrics/ops/py_metrics_ops.py line 23 there is a "metrics_ops.so" required. But could i get it?

**Comment by yuningchai** [comment]
Hi there,

Thank you for your interests! The lib is compiled at installation. The easiest way to install is via pip if you have a Linux distribution: https://github.com/waymo-research/waymo-open-dataset/blob/master/docs/quick_start.md

Otherwise, you'll need to follow the [compilation](https://github.com/waymo-research/waymo-open-dataset/blob/master/docs/quick_start.md#local-compilation-without-docker-system-requirements) instructions.

**Comment by lezipg** [comment]
Thanks! I've looking for the lib from build but forgot these have been installed via pip...
