### ISSUE TITLE
Example of generating MotionChallengeSubmission protos?

### ISSUE THREAD

**Issue by roggirg** [waymo-research/waymo-open-dataset#299]
Is there an example script for generating the MotionChallengeSubmission protos? 
Say, for every scenario, I have a set of 6 trajectories for each agent in the scene (working with pytorch), how do I generate a submission file?
Thanks!

**Comment by scott-ettinger** [comment]
Hi Roger, 

This python pseudo-code (untested) gives the general idea of how to create a 
submission for the motion prediction challenge. It assumes you have an object 
called my_predictions that contains a list of agents each of which has a list of 
predictions. The predictions are assumed to be 10Hz corresponding to the 
scenario proto's future time steps. To create a submission for the interactive 
prediction challenge, you will need to appropriately set the joint_prediction 
field rather than the single_predictions field.  Hopefully you can adapt this to 
your work flow.

```

# Create a submission proto.
submission = motion_submission_pb2.MotionChallengeSubmission()
submission.submission_type = motion_submission_pb2.MotionChallengeSubmission.MOTION_PREDICTION
# Set the other metadata fields in the submission proto.
# The account name field must match the email address you register with.

# Create a ChallengeScenarioPredictions proto for each scenario.
for scenario in scenarios:
    my_predictions = predict(scenario)
    scenario_predictions = motion_submission_pb2.ChallengeScenarioPredictions()
    scenario_predictions.scenario_id = scenario.scenario_id

    # Add a SingleObjectPrediction for each agent.
    for agent in my_predictions:
      prediction = motion_submission_pb2.SingleObjectPrediction()
      prediction.object_id = agent.id

      # Add a ScoredTrajectory for each agent prediction.
      for trajectory in agent.predictions:
        scored_trajectory = motion_submission_pb2.ScoredTrajectory()
        scored_trajectory.confidence = trajectory.confidence

        # Subsample the prediction output to the required 2 Hz. 
        subsample_factor = 5
        count = 0
        for point in trajectory.points:
          count += 1
          if count == subsample_factor:
            scored_trajectory.trajectory.center_x.append(point.x)
            scored_trajectory.trajectory.center_y.append(point.y)
            count = 0
        prediction.trajectories.append(scored_trajectory)

      # Add the agent predictions to the ChallengeScenarioPredictions object.
      scenario_predictions.single_predictions.predictions.append(prediction)

    # Add the scenario predictions to the submission.
    submission.scenario_predictions.append(scenario_predictions)

```

**Comment by roggirg** [comment]
This is great, thanks Scott!

**Comment by ArielleZhang** [comment]
Could you elaborate on the confidence score for each trajectory? In the proto definition, there is a comment saying: 
`  // An optional confidence measure for this joint prediction. These confidence
  // scores should reflect confidence in the existence of the trajectory across
  // scenes, not normalized within a scene or per-agent.`
  so if I am understanding correctly, the scores should be the trajectories scored across different scenes rather than within one scene right? For example if in scene1 I have traj0, traj1, and in scene2 I have traj1, then the score for traj1 should be normalized across all scenes (scene1, scene2) rather than scores for traj0 and traj1 are normalized within scene1?

Thanks
