### ISSUE TITLE
How to know Camera's Position of the input image in 2D Detection?

### ISSUE THREAD

**Issue by DuongTran1708** [waymo-research/waymo-open-dataset#309]
Dear Committee,

In the submission structure "wod_latency_submission" for 2D detection, we only get the **DATA_FIELDS = ['FRONT_IMAGE']** for the FRONT camera, because the function **run_model(IMAGE)** only gets the np.ndarray.

[model.py](https://github.com/waymo-research/waymo-open-dataset/blob/a19ba044e0ad42c49e95f09298b491db5d8ed05c/waymo_open_dataset/latency/examples/2d_challenge/tensorflow/wod_latency_submission/model.py#L25)

[__init.py__](https://github.com/waymo-research/waymo-open-dataset/blob/a19ba044e0ad42c49e95f09298b491db5d8ed05c/waymo_open_dataset/latency/examples/2d_challenge/pytorch/wod_latency_submission/__init__.py#L21)

- How to know Camera's Position of the input image in 2D Detection?
- If yes, how we can get this?
- Or, Do we have to predefined like this 
```python
DATA_FIELDS = ['FRONT_IMAGE','FRONT_LEFT_IMAGE','SIDE_LEFT_IMAGE']
```

Thank you for reading, and I hope to see your respond soon.

**Comment by sabeekpradhan** [comment]
Hi Duong,

For the 2D detection challenge, you shouldn't need to know the position or calibration of the camera, because the ground truth that you are evaluated against is in pixel space, not 3D coordinates. 

If you're using the camera to help with _3D_ detection, then you can add more of the fields defined [here](https://github.com/waymo-research/waymo-open-dataset/tree/master/waymo_open_dataset/latency#data-formats) to the DATA_FIELDS list. You would then need to make sure that your `run_model` function takes in each of those fields as keyword arguments. For example, if you have 
```DATA_FIELDS = ['FRONT_IMAGE', 'FRONT_INTRINSIC', 'FRONT_EXTRINSIC', 'FRONT_POSE']```
Then you would need to do
```def run_model(FRONT_IMAGE, FRONT_INTRINSIC, FRONT_EXTRINSIC, FRONT_POSE):```
So that your model is taking in all the data fields. You can see [here](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/latency/wod_latency_evaluator.py#L63-L71) how your `run_model` function will ultimately be called.

Hope this helps!

**Comment by DuongTran1708** [comment]
@sabeekpradhan Thank for you answers! It help me a lot.
