### ISSUE TITLE
Motion dataset

### ISSUE THREAD

**Issue by MeiHuanshan** [waymo-research/waymo-open-dataset#323]
Thank you for releasing so amazing dataset for motion forecast task, but I have some qusetions.
**First, what's the meaning of waymo_open_dataset_motion_v_1_0_0/uncompressed/scenario? Scenario files is one-to-one correspondent to tf_example files?**
**Second, How to parse scenario tfrecord? I can parse tf_example tfrecord according to tutorial/tutorial_motion.ipynb.**
**Third**, in "Large Scale Interactive Motion Forecasting for Autonomous Driving : The WAYMO OPEN MOTION DATASET"  3.1. Mining for interesting scenarios, we can see "With this framework, we specifically mined for the following pairwise interaction scenarios: merges, lane changes, unprotected turns, intersection left turns, intersection right turns, pedestrian-vehicle interactions, cyclistvehicle interactions, interactions with close proximity, and interactions with high accelerations". **And how to get that eight tags**?
**Forth, when I parse tf_examples, I can't get types of lane boundary lines, road edges, stop signs, crosswalks, and speed bumps** but that is mentioned in paper of 3. Dataset

**Comment by scott-ettinger** [comment]
Hi Mei. 

1. Each tf.Example record in the tf_example files corresponds to a Scenario proto record in the scenario files.  The tf.Examples are generated by converting the Scenario proto into tensors.  The two forms are almost identical information with the limitation that some information can be truncated in the tf.Examples due to the fixed tensor sizes.  The full set of features available are listed here : https://waymo.com/open/data/motion/tfexample

2. The tf.record files can be parsed as shown in the tutorial.  Please let me know if this does not answer your question. 

3. For the validation and test sets, there is a feature in the tf.Examples called state/tracks_to_predict or in the Scenario protos, the tracks_to_predict field. This indicates which objects need to be predicted.  For the interactive sets, there are 2 objects to be predicted while in the non-interactive datasets, there are up to 8 objects to be predicted.  Again, please let me know if this does not answer your question.

4. If you parse the tf.Example data, you should get the tensors from the features roadgraph_samples/xyz and roadgraph_samples/type.  Each point in the roadgraph_samples/xyz tensor has a corresponding type in the roadgraph_samples/type tensor that indicates if it is a lane center, lane boundary, etc.  A full description of the types is on this page : https://waymo.com/open/data/motion/tfexample.

**Comment by MeiHuanshan** [comment]
Thank you for your particular replay. I got it.
