### ISSUE TITLE
Load waymo scenario data?

### ISSUE THREAD

**Issue by MoritzNekolla** [waymo-research/waymo-open-dataset#343]
How do I load the waymo motion scenario files (Scenario protocol buffers)? According to the tutorial, this should work:

```python
FILENAME = "uncompressed_scenario_testing_testing.tfrecord-00000-of-00150"
dataset = tf.data.TFRecordDataset(FILENAME, compression_type='')
for data in dataset:
    frame = open_dataset.Frame()
    frame.ParseFromString(bytearray(data.numpy()))
    break
```

However, I get "Error parsing message". Nevertheless, loading tf.example is no problem when utilizing:

```python
dataset = tf.data.TFRecordDataset(FILENAME, compression_type='')
data = next(dataset.as_numpy_iterator())
parsed = tf.io.parse_single_example(data, features_description)
```

Unfortunately, this does not work for the scenario data, because I dont know the feature_description of the data... or I am unable to understand detailed explanation of waymo i.e. how to use .proto file?

Could somebody help me to not only load data but to understand the basic architecture of the dataset

Thanks

**Comment by scott-ettinger** [comment]
Hi, 
The tutorial is only written to use the tf.Example dataset.  The scenario format data is stored as serialized Scenario protocol buffers (the two versions of the dataset contain basically the same data in a different format).  
To decode the scenario protos you can do something like this : 

```
FILENAME = "uncompressed_scenario_testing_testing.tfrecord-00000-of-00150"
raw_dataset = tf.data.TFRecordDataset([FILENAME])
for raw_record in raw_dataset.take(1):
  proto_string = raw_record.numpy()
  proto = scenario_pb2.Scenario()
  proto.ParseFromString(proto_string)
  print(proto)
  break
```

This will print the first Scenario proto in the file.  You will need to import the compiled scenario_pb2 protocol buffer python module.  If you need more information on protocol buffers this link may help: https://developers.google.com/protocol-buffers/docs/pythontutorial.

**Comment by MoritzNekolla** [comment]
Hi Scott,

thanks for answering. With your help I was able to run:
`python
import numpy as np
from waymo_open_dataset.protos import scenario_pb2 

FILENAME = '../data/scenario/uncompressed_scenario_training_20s_training_20s.tfrecord-00000-of-01000'
dataset = tf.data.TFRecordDataset(FILENAME)
scenario_data = []
for data in dataset:
    proto_string = data.numpy()
    proto = scenario_pb2.Scenario()
    proto.ParseFromString(proto_string)
    scenario_data.append(proto)
`
Afterwards call you filed of interest:
`scenario_data[x].<your_Filed>`

**Comment by EnnaSachdeva** [comment]
For data in the dataset:
    proto_string = data.NumPy()
    proto = scenario_pb2.Scenario()
    proto.ParseFromString(proto_string)
    scenario_data.append(proto)

Why does **dataset** from each scenario_proto tf file contain several hundreds of **data** inside it? Since each **data** already has timestamps, I don't believe **data** corresponds to data at each time step of that particular scenario. If not, does it represent several hundred different scenarios? 
Any help in a better understanding of this data format would be appreciated.

**Comment by EnnaSachdeva** [comment]
> 

What does hundreds of data in dataset represent here? Since each data already has timestamps and contains states and other information from time 0->T, I don't believe data corresponds to the data at each time step of that particular scenario. If not, does it represent several hundred different scenarios?
Any help in a better understanding of this data format would be appreciated.

**Comment by EnnaSachdeva** [comment]
> Hi, The tutorial is only written to use the tf.Example dataset. The scenario format data is stored as serialized Scenario protocol buffers (the two versions of the dataset contain basically the same data in a different format). To decode the scenario protos you can do something like this :
> 
> ```
> FILENAME = "uncompressed_scenario_testing_testing.tfrecord-00000-of-00150"
> raw_dataset = tf.data.TFRecordDataset([FILENAME])
> for raw_record in raw_dataset.take(1):
>   proto_string = raw_record.numpy()
>   proto = scenario_pb2.Scenario()
>   proto.ParseFromString(proto_string)
>   print(proto)
>   break
> ```
> 
> This will print the first Scenario proto in the file. You will need to import the compiled scenario_pb2 protocol buffer python module. If you need more information on protocol buffers this link may help: https://developers.google.com/protocol-buffers/docs/pythontutorial.

What do hundreds of **data** in **dataset** represent here? Since each **data** already has timestamps and contains states and other information from time 0->T timestep, I don't believe **data** corresponds to the data at each time step of that particular scenario. If not, does it represent several hundred different scenarios?
Any help in a better understanding of this data format would be appreciated.

**Comment by EnnaSachdeva** [comment]
> Hi Scott,
> 
> thanks for answering. With your help I was able to run:
> 
> ```python
> import numpy as np
> from waymo_open_dataset.protos import scenario_pb2 
> FILENAME = '../data/scenario/uncompressed_scenario_training_20s_training_20s.tfrecord-00000-of-01000'
> dataset = tf.data.TFRecordDataset(FILENAME)
> scenario_data = []
> for data in dataset:
>     proto_string = data.numpy()
>     proto = scenario_pb2.Scenario()
>     proto.ParseFromString(proto_string)
>     scenario_data.append(proto)
> ```
> 
> Afterwards call you field of interest:
> 
> `scenario_data[x].<your_Field>`

What do hundreds of **data** in **dataset** represent here? Since each **data** already has timestamps and contains states and other information from time 0->T timestep, I don't believe **data** corresponds to the data at each time step of that particular scenario. If not, does it represent several hundred different scenarios under one **dataset**?
Any help in a better understanding of this data format would be appreciated.

**Comment by scott-ettinger** [comment]
Hi, 
Each file in the dataset is a tfrecord file containing many different Scenarios.  Each scenario is an independent example containing both agent motion data and map data.  In the code above, the data variable contains a string representing a single Scenario proto record from the file which gets parsed into a Scenario protocol buffer object.

The full training dataset is broken into 1000 files or "shards" each of which contains many Scenario protocol buffer objects. This is done in order to facilitate processing in parallel and to keep file sizes smaller.

You can find more details on the tfRecord file format here: https://www.tensorflow.org/tutorials/load_data/tfrecord

**Comment by EnnaSachdeva** [comment]
> 

That totally makes sense. Thanks for the clarification.

**Comment by EnnaSachdeva** [comment]
> Hi, Each file in the dataset is a tfrecord file containing many different Scenarios. Each scenario is an independent example containing both agent motion data and map data. In the code above, the data variable contains a string representing a single Scenario proto record from the file which gets parsed into a Scenario protocol buffer object.
> 
> The full training dataset is broken into 1000 files or "shards" each of which contains many Scenario protocol buffer objects. This is done in order to facilitate processing in parallel and to keep file sizes smaller.
> 
> You can find more details on the tfRecord file format here: https://www.tensorflow.org/tutorials/load_data/tfrecord

That totally makes sense. Thanks for the clarification.
