### ISSUE TITLE
No lanes' connectivity data in motion dataset?

### ISSUE THREAD

**Issue by iyuner** [waymo-research/waymo-open-dataset#359]
Hi! 

I found in the [map](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/protos/map.proto) proto file, it defines fields like `left_neighbors` `right_neighbors` `entry_lanes` `exit_lanes`  for the `LaneCenter` message. However, in the training data of the scenarios files, these fields are all empty. Could we find the information of lanes' connectivity somewhere? 

Thanks!

**Comment by MoritzNekolla** [comment]
I think you are referring to my issue [https://github.com/waymo-research/waymo-open-dataset/issues/349](url).
Unluckily, there is no solution yet.

**Comment by iyuner** [comment]
Hi! Thanks! Yea, I think you are right. Also, refer to #278, there will be an upcoming release that will contain this info. Since this issue is duplicated, I will close it now :)

**Comment by dongb5** [comment]
Hi, have you tried the 1.1 version data? I used the 1.4.1 waymo_open_dataset API installed through pip and 1.1 version data, but could not get the information of connectivity. Seems that the proto definition of installed waymo_open_dataset still does not have the lanes' connectivity.

**Comment by MoritzNekolla** [comment]
Hey,

 

sorry for the late response.

 

I'm currently using 1.1 and I can load connectivity and such. The problem is, that it often makes no sense. Connective lanes are either far away or even contrary.

Unfortunately, scott is not answering to this.


 

Greetings

 

Gesendet: Dienstag, 18. Januar 2022 um 10:31 Uhr
Von: "Zheng Liu" ***@***.***>
An: "waymo-research/waymo-open-dataset" ***@***.***>
Cc: "Ollowain" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [waymo-research/waymo-open-dataset] No lanes' connectivity data in motion dataset? (#359)


 

Hi, have you tried the 1.1 version data? I used the 1.4.1 waymo_open_dataset API installed through pip and 1.1 version data, but could not get the information of connectivity. Seems that the proto definition of installed waymo_open_dataset still does not have the lanes' connectivity.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dongb5** [comment]
> Hey,   sorry for the late response.   I'm currently using 1.1 and I can load connectivity and such. The problem is, that it often makes no sense. Connective lanes are either far away or even contrary. Unfortunately, scott is not answering to this.   Greetings   Gesendet: Dienstag, 18. Januar 2022 um 10:31 Uhr Von: "Zheng Liu" ***@***.***> An: "waymo-research/waymo-open-dataset" ***@***.***> Cc: "Ollowain" ***@***.***>, "Comment" ***@***.***> Betreff: Re: [waymo-research/waymo-open-dataset] No lanes' connectivity data in motion dataset? (#359)   Hi, have you tried the 1.1 version data? I used the 1.4.1 waymo_open_dataset API installed through pip and 1.1 version data, but could not get the information of connectivity. Seems that the proto definition of installed waymo_open_dataset still does not have the lanes' connectivity. — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***>

Exactly. I can load the connectivity as well by copying the proto files from the sources into my own workspace. And I also found that the connections of lanes are a bit of a mess.

**Comment by titas0602** [comment]
Hi, I'm working on loading the lane connectivity info from the Waymo dataset. However, I'm stuck because I'm not sure how to load the data form the tf record using the proto definition. If you could share a minimum working example of loading lane connectivity data from a tf record file, that'd be really helpful. Thanks!

**Comment by MoritzNekolla** [comment]
You mean simply loading the data? 
Run:
`python
import numpy as np
from waymo_open_dataset.protos import scenario_pb2 
FILENAME = '../data/scenario/uncompressed_scenario_training_20s_training_20s.tfrecord-00000-of-01000'
dataset = tf.data.TFRecordDataset(FILENAME)
scenario_data = []
for data in dataset:
    proto_string = data.numpy()
    proto = scenario_pb2.Scenario()
    proto.ParseFromString(proto_string)
    scenario_data.append(proto)
`

If you need an example for accessing lane_neighbors etc. take a look into this issue: [issue](https://github.com/waymo-research/waymo-open-dataset/issues/389)
I posted a picture (sorry) of some exemplary code.

**Comment by titas0602** [comment]
Thanks a lot! I can load the lane data now.

**Comment by iyuner** [comment]
One question, to get the connectivity info, it seems we can only use the protocol buffer format data, but not the tfexample format data? As shown in the [tutorials](https://github.com/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial_motion.ipynb), the tfexample doesn't update the `features_description` to the v1.1 version. Is that right?

**Comment by titas0602** [comment]
That is correct. You need the data in the proto format, not in the tf example format because only the proto format has the features updated in v1.1.
