### ISSUE TITLE
Camera 5 often has shifted human keypoint annotations

### ISSUE THREAD

**Issue by fabianwindbacher** [waymo-research/waymo-open-dataset#458]
When looking at the human keypoint annotations I found that some seem completely off.
However, these issues seem to be very common with camera 5, and less so with all the others.

![image](https://user-images.githubusercontent.com/33809377/164454672-e85ac2a9-262a-447f-a093-c2ac1143d309.png)
![image](https://user-images.githubusercontent.com/33809377/164454810-a98c2b81-1789-4e08-8b4b-f52a43a9337a.png)
![image](https://user-images.githubusercontent.com/33809377/164454852-c20090bf-f0a6-41db-80d1-d83f90ef6f30.png)
![image](https://user-images.githubusercontent.com/33809377/164455271-d2539854-aae6-4618-bcaf-e342790136de.png)

but it is not always off, here are examples of cam 5 being correct:
![image](https://user-images.githubusercontent.com/33809377/164454962-2724fc4d-6bb5-4b72-99a2-6a120d8c14e9.png)
![image](https://user-images.githubusercontent.com/33809377/164455125-a394523f-ad7e-4b8c-9e35-63cfbd0e14af.png)

What is the reason for this? Should one maybe drop camera 5 annotations?

**Comment by alexgorban** [comment]
Thanks a lot for reporting this issue!

It looks like a bug related to the camera's region of interest. I'll investigate and try to fix it in the next dataset/software update.

Meanwhile, can you please share context names for frames where you observed this issue?

**Comment by fabianwindbacher** [comment]
For example:
8302000153252334863_6020_000_6040_000
17694030326265859208_2340_000_2360_000
18446264979321894359_3700_000_3720_000
8302000153252334863_6020_000_6040_000

Also, I found some similar issues with cam 4 as well (they felt more rare than with cam 5), e.g.:
8302000153252334863_6020_000_6040_000

I did not find such examples for cam 1-3

**Comment by alexgorban** [comment]
Thanks a lot for sharing! We identified the root case of the issue and will include a fix in the next release. Please stay tuned.

**Comment by alexgorban** [comment]
This issue was fixed in the latest dataset release [v1.3.2](https://pantheon.corp.google.com/storage/browser/waymo_open_dataset_v_1_3_2):

For example:

`frame.context.name = "18446264979321894359_3700_000_3720_000"`, `frame.timestamp_micros=1557267727073927` SIDE_RIGHT camera has the following keypoints:
![1557267727373756-SIDE_RIGHT](https://user-images.githubusercontent.com/1524085/167534909-844a54a8-67b5-43ee-9601-67887cb2bc88.png)

in v1.3.1 some of these keypoints were incorrectly shown for `frame.timestamp_micros=1557267727173872` (in v1.3.2 this frame has no keypoints).

**Comment by liyingyanUCAS** [comment]
@alexgorban @fabianwindbacher  Thank you for your contribution! I recently want to use the 3D keypoints of humans, but I can only use v1.3.1. Can you tell me whether the problem only occurs in 2D keypoints or both 2D/3D keypoints? Thanks a lot.
