### ISSUE TITLE
Frame.pose and frame.timestamp_micros not relating to the same thing?

### ISSUE THREAD

**Issue by zgojcic** [waymo-research/waymo-open-dataset#464]
Hi, 

I would like to clarify one thing in the dataset.proto file. Each `Frame`  message contains `pose` and `timestamp_micros` and I always operated under the assumption that the pose defines the position of the car at time `timestamp_micros`. However, the `frame.pose` is the same as the pose in ` frame.images[0].pose` but the ` frame.images[0].pose_timestamp * 1e6 != frame_timestamp_micros`. Upon reading through the issues, I think now believe that `frame.pose` defines the pose of the car at the **middle of the lidar** spin (and the moment when front camera is triggered as they are synchronized), but on the other hand `frame.timestamp_micros` is he timestamp of the **start of the lidar frame**. Is my understanding correct now? 

If this is actually the case, I think it should be explicitly noted in the dataset.proto that `frame.timestamp_micros` is **not** the timestamp of `frame.pose` as other researchers might also assume that.

Thank you for your help
Zan

**Comment by VincentCa** [comment]
Hi Zan,

Thanks for your feedback! You are right that `frame.pose` and `frame.timestamp_micros` are not corresponding. We understand that this is confusing, especially since there exists such a correspondence in `CameraImage` between `pose` and `pose_timestamp`, and we also understand that it is also not clearly documented.

You are right that `frame.timestamp_micros` is the timestamp of the start of the LiDAR spin, and `frame.pose` defines the vehicle pose *near* the middle of the LiDAR spin. One caveat is that `frame.pose` is not guaranteed to always exactly equal the front camera image pose because of slight synchronization differences, although it can be the case.

We will revise the documentation in `dataset.proto` to reflect this more clearly. Please let us know if you have any other questions or additional feedback.

Best,
Vincent, on behalf of the Waymo Open Dataset team
