### ISSUE TITLE
Principle of choosing the range of the local HD map in motion dataset

### ISSUE THREAD

**Issue by tianqi-wang1996** [waymo-research/waymo-open-dataset#466]
Hello, I would like to know the principle that determines the range of the local HD map in the motion dataset. I cannot find the description of it on the paper or the website and I have also tried to download several tf_example files to find out by myself, but I still can not figure out how it works.

Is the submap moving with the ego vehicle (the self-driving car)? For example, include the submap information  of [100m, -100m] range in ego's x-direction and [150m, -150m] range in ego's y-direction? (Taking ego's rotation into consideration)

Moreover, I noticed a strange thing that confuses me. I expected one tf_example file contains all the data for several scenarios, which means there should some consecutive samples that have the same scenario id, however, I found that in my tested file (xxxxx_training_tf_example.tfrecod-00550-of-01000), all the 424 samples have different scenario ids, which confuses me.

**Comment by scott-ettinger** [comment]
Hello, 
The map data contains approximately a 100m radius around the path of the autonomous vehicle in the scenario. 

For the tf.Example files, each file contains many examples each of which has a unique scenario ID.  Each window of the 20 second segments is considered a separate scenario even though some of them may overlap in time.  Also, each of the 20 second training examples also have unique scenario IDs that are distinct from the 9.1 second examples. Please let me know if you still have questions regarding this.

**Comment by tianqi-wang1996** [comment]
Hello scott,

Thanks for your quick response. 
The reason that I ask for those information is that I want to align my customized dataset generated from the simulator with the waymo format, so I would like to know the format more precisely and as well as the reason of it.

Regarding the two questions that I raised, I still have some additional questions.
1. Can you provide a more precise definition of the submap range for each sample? Is it just a circle range with 100m radius centered at the autonomous vehicle? If so, can we guanrantee that all the target vehicles that we tend to predict locate inside that moving submap across the whole scenario?
2. Why do you have different scenario IDs for all the examples contained in one tf_example.tfrecord file? Shouldn't the examples of the same scenario have the same scenario id and be ordered as consecutive examples in one file? If the answer is no, then how can we extract all the examples for one certain scenario?

Looking forward to your reply!

**Comment by scott-ettinger** [comment]
Hello, 
1. To get the submap for an example, a circle of radius 100 meters is traced along the path of the autonomous vehicle. A polygon is created from the convex hull of these circles and all map features that intersect with the polygon are included for the example.  Since we include features that only partially touch this polygon, the radius is only approximate.   The range of the offline perception algorithm used to detect objects in the sensor data to create the dataset is less than 100m so the objects to be predicted should fall within this radius.

2. The examples in a single tfrecord file are randomly distributed. They do not necessarily have any relationship to one another.  I agree the term scenario has not been precisely defined. We consider each example a "scenario".  While there may be a small number of examples that overlap in time from the same log data, they each have a different history and starting state at the prediction time and have a different future to predict.  For context, the 9.1 second examples are generated by creating overlapping windows from 20 second segments  - 7 windows for training sets, and 3 for validation and testing.  

For the last part of your question, if you are asking if you can get all of the 9.1 scenarios generated from the 20 second run segment, there is currently not any good way to do that.  We do provide the full 20 second run segments for the training data in the scenario proto format only in the directory : waymo_open_dataset_motion_v_1_1_0/uncompressed/scenario/training_20s . 

Please let me know if you have further questions.
