### ISSUE TITLE
validation vs. validation_interactive

### ISSUE THREAD

**Issue by eugenevinitsky** [waymo-research/waymo-open-dataset#473]
Apologies if this was in the documentation or logs but after a bunch of searching through the documentation and paper I am struggling to figure out what the difference between validation and validation_interactive is in the motion dataset? Am I correct in assuming that one set contains the mined data?

Thank you!

**Comment by scott-ettinger** [comment]
Hi, 
Last year we held both the motion prediction challenge and the interaction prediction challnge (https://waymo.com/open/challenges/2021/interaction-prediction/) which requires joint prediction of 2 agents rather than independent predictions for up to 8 agents.  The interactive files are for the interactive prediction challenge (the interaction challenge leaderboard can still be used for research).  For this year's challenge, you must use the files without the _interactive suffix.

**Comment by eugenevinitsky** [comment]
Hi Scott,

Thank you so much again for the help! That clarifies things.
