### ISSUE TITLE
3D Camera-Only object visible

### ISSUE THREAD

**Issue by Birdylx** [waymo-research/waymo-open-dataset#531]
I follow the tutorial_camera_only.ipynb to visualize the 3d bbox on image, but there is a strange situation in the visualization results.
<img width="318" alt="image" src="https://user-images.githubusercontent.com/29754889/182082778-b66d2256-b6ab-47a0-b178-8b7744c7789e.png">
some objects are invisible and blocked by the truck, but these objects still have a 3d bbox. why? I think it is very hard for model to predict these invisible object bbox. 
I have some questions here:
1. if i want to train a camera object detection model, should i filter these invisible bbox? and point cloud has the similar problem, no point on the object, but still labeled 3d bbox.
2. if these bboxes should be filtered, how to do that?

**Comment by VincentCa** [comment]
Hi! 

Please take a look at the `num_top_lidar_points_in_box` field, see also our description on the [challenge page](https://waymo.com/open/challenges/2022/3d-camera-only-detection/). This field will be available if you use dataset V1.3.2 or later, and only counts points-in-box from the top LiDAR which is located quite close to the cameras. We use this as a rough proxy for determining visibility of objects. We highly recommend applying visibility filtering.

This filter is actually applied in the tutorial. I would recommend checking the point counts for all of these boxes. If zero, make sure you are applying the filter as intended. If non-zero, which I suspect may be the case here, then you have found an interesting edge-case since the laser can pass through windows but depending on the situation, you may not see through with the cameras, at least not very well.

Hope this helps!

**Comment by Birdylx** [comment]
@VincentCa Thanks for you reply！Your answer helps me a lot, I found that I missed the `num_top_lidar_points_in_box` filed in the tutorial.
