### ISSUE TITLE
Two questions about the cameras

### ISSUE THREAD

**Issue by dkoalal** [waymo-research/waymo-open-dataset#549]
Hi, thank you for your excellent dataset !
I'd like to ask some questions about the camera itself.

The first question is that why do you use cameras with 'rolling shutter' rather than 'global shutter'? 
And why don't you have cameras with rear view? 

Thanks a lot!

**Comment by VincentCa** [comment]
Hi,

Thanks for your questions! Unfortunately, due to IP reasons, I'm unable to provide an answer to the first question.

Regarding your second question, we don't have this now, but we're always considering to expand the dataset to make it more useful to the community. If you can share more about your use case of the rear facing camera, we can take it into account for future releases.

Best,
Vincent

**Comment by dkoalal** [comment]
Thank you very much for your response!
