### ISSUE TITLE
How to make submission for the motion prediction leaderboard?

### ISSUE THREAD

**Issue by ggosjw** [waymo-research/waymo-open-dataset#573]
Hi, thank you for open-sourcing your great work.

I have a question regarding how to make a submission for the motion prediction leaderboard.

Could you give me some intuitive suggestions?

I really appreciate any help you can provide.

**Comment by scott-ettinger** [comment]
The general procedure is to run inference on your model for every example in the test dataset and store the predictions into a [MotionChallengeSubmission protocol buffer object](https://github.com/waymo-research/waymo-open-dataset/blob/17f070076dad149766357b31e25d27cf8b5da6ac/waymo_open_dataset/protos/motion_submission.proto#L125).  Create the proto and be sure to populate the account_name field with the same emal address you used to register on the Waymo Open Dataset website.  Be sure to correctly fill out the submission_type field depending on if you are using the standard test set or the interactive test set.  Please also fill out the unique_method_name, authors, and description fields and optionally the method_link with a URL to any documentation.  

After creating the proto, fill in the scenario_predictions field with a single [ChallengeScenarioPredictions message](https://github.com/waymo-research/waymo-open-dataset/blob/17f070076dad149766357b31e25d27cf8b5da6ac/waymo_open_dataset/protos/motion_submission.proto#L102) for each example in the dataset.   If you are participating in the interactive challenge, populate the joint_predictions field in the prediction_set oneof, otherwise populate the single_predictions field.  To populate these, add the trajectories predicted by your model for each agent in the example's tracks_to_predict field to either the PredictionSet or JointPrediction messages using the format defined [here](https://github.com/waymo-research/waymo-open-dataset/blob/17f070076dad149766357b31e25d27cf8b5da6ac/waymo_open_dataset/protos/motion_submission.proto#L23).

Please let us know if you have further questions.

**Comment by ggosjw** [comment]
Thank you for your helpful comments!

**Comment by ggosjw** [comment]
Hi, thank you for open-sourcing your great work.

I have a question regarding my submission for the motion prediction leaderboard.

When I uploaded the validation submission, I encountered the following error information:
![image](https://user-images.githubusercontent.com/87901530/205914777-598655a2-11cd-4bd9-abde-1103a10f2758.png)
However, when I check the scenario: 4e3b488f1d96ea29, using code:
![image](https://user-images.githubusercontent.com/87901530/205915185-47e0db78-dd1a-4b40-8b0c-03fcd109f553.png)

I found that 
![image](https://user-images.githubusercontent.com/87901530/205916015-3a6ca516-7171-4c36-845d-62ee8920619f.png)
This is contradicting the error information. And the total number of tracks is 148, much smaller than 600.

So, could you give me some intuitive suggestions regarding this error?

I really appreciate any help you can provide.

**Comment by BJHYZJ** [comment]
I have also encountered some problems with the submission. Could you please provide some simple examples to explain how to submit and in what form to submit the results? I really appreciate any help if you could reply to me, it will be very important to me.
