### ISSUE TITLE
Camera poses for the Waymo Block-NeRF dataset

### ISSUE THREAD

**Issue by wuzirui** [waymo-research/waymo-open-dataset#585]
Thanks for your work on the Waymo datasets. In the [waymo-block-nerf dataset](https://waymo.com/research/block-nerf/?ncr), I didn't find a camera pose field (extrinsic) but only ray parameters. Could you please provide the raw camera poses as well?

By the way, are the camera hash ids sorted by the captured time?

Thank you very much!

**Comment by VincentCa** [comment]
Hi, thank you for your interest in the Waymo Block-NeRF dataset! Unfortunately, we can not provide the camera extrinsic parameters in isolation due to IP reasons, and they were abstracted away into the ray parameters. However, you may be able to approximately estimate them using traditional SFM methods.

Also, please note that the capture time/order of the individual frames is not provided. `cam_idx` is simply identifying the different cameras, and `image_hash` is a unique hash that is neither ordered nor connected to the image capture time.

Hope this helps!
Vincent
