### ISSUE TITLE
v2 convert range image to point cloud seems not right

### ISSUE THREAD

**Issue by Rambo8248** [waymo-research/waymo-open-dataset#656]
I try to convert the range image to point cloud but it seems not right. The pipeline is as follows:

1. download the v2 dataset
![2023-05-03 10-40-07 的屏幕截图](https://user-images.githubusercontent.com/81836701/235823388-d389e52d-86d8-4f3a-a2d2-8a21ab10718f.png)
![2023-05-03 10-40-14 的屏幕截图](https://user-images.githubusercontent.com/81836701/235823418-e63f0f80-2b06-4b91-a2f8-c1279aaef37c.png)

2. specify the context
```
dataset_dir = '/media/alv-2/Rambo/Data/waymo/v2'
context_name = '15832924468527961_1564_160_1584_160'
```

3. load the frames

```
def read(tag: str) -> dd.DataFrame:
  paths = tf.io.gfile.glob(f'{dataset_dir}/{tag}/{context_name}.parquet')
  return dd.read_parquet(paths)
```

```
lidar_df = read('lidar')
lidar_pose_df = read('lidar_pose')
lidar_calibration_df = read('lidar_calibration')
lidar_segmentation_df = read('lidar_segmentation')
stats_df = read('stats')
vehicle_pose_df = read('vehicle_pose')

_, lidar_row = next(iter(lidar_df.iterrows()))
_, lidar_pose_row = next(iter(lidar_pose_df.iterrows()))
_, lidar_calibration_row = next(iter(lidar_calibration_df.iterrows()))
_, lidar_segmentation_row = next(iter(lidar_segmentation_df.iterrows()))
_, vehicle_pose_row = next(iter(vehicle_pose_df.iterrows()))

lidar = v2.LiDARComponent.from_dict(lidar_row)
lidar_pose = v2.LiDARPoseComponent.from_dict(lidar_pose_row)
lidar_calibration = v2.LiDARCalibrationComponent.from_dict(lidar_calibration_row)
lidar_segmentation = v2.LiDARSegmentationLabelComponent.from_dict(lidar_segmentation_row)
vehicle_pose = v2.VehiclePoseComponent.from_dict(vehicle_pose_row)
```

4. call the converting function to convert range image to points

```
from waymo_open_dataset.v2.perception.utils import lidar_utils
points = lidar_utils.convert_range_image_to_point_cloud(lidar.range_image_return1,
                                                        lidar_calibration,
                                                        lidar_pose.range_image_return1,
                                                        vehicle_pose,
                                                        False)
```

then the points seems to be in spherical coordinate
![2023-05-03 10-45-09 的屏幕截图](https://user-images.githubusercontent.com/81836701/235823848-c46c3319-688b-4350-9308-559445f11649.png)
![2023-05-03 10-46-32 的屏幕截图](https://user-images.githubusercontent.com/81836701/235823966-0bd7162a-2d7f-4b8b-ad66-a008993a0bdf.png)

i wonder whether the **data got wrong** or the `convert_range_image_to_point_cloud` function is **still under developing**?
can somebody help me?

**Comment by JingweiJ** [comment]
Hi @Rambo8248 ,

Thank you for using WOD v2. The cause of this issue is that rows in `lidar`, `lidar_pose`, `lidar_calibration` parquet files do not necessarily have keys following the same order. In this case, the first row in `lidar_df` has key with `laser_name == 1`, while the first row in `lidar_calibration_df` has `laser_name == 2`. Instead, the last row in `lidar_calibration_df` has `laser_name == 1`. I tried loading the last row in `lidar_calibration_df` and ran conversion and visualization, the result looks correct.

While investigating this issue, I realized that a fix is needed in this [line](https://github.com/waymo-research/waymo-open-dataset/blob/1eabddad78858a74b18152f61b89868a6c4ecc59/src/waymo_open_dataset/v2/perception/utils/lidar_utils.py#L92). A hot fix is to change it into:
```  if calibration.beam_inclination.values is not None:```
We'll fix this line in the next commit coming soon.
