### ISSUE TITLE
Unknown error when submitting for evaluation against the Validation Set,

### ISSUE THREAD

**Issue by lmbneuron** [waymo-research/waymo-open-dataset#657]
specify submission_key=user_id: "zhenghaotian1998@163.com" submission_id: "1683182935991837".
![image](https://user-images.githubusercontent.com/93885679/236132185-fea80551-29a3-4242-8de0-79407d82e3d6.png)

**Comment by alexzzhu** [comment]
Hi, could you clarify which challenge this is for?

**Comment by nicomon24** [comment]
This is for sim agents, let me have a look!

**Comment by nicomon24** [comment]
Hi @lmbneuron, it seems the error is caused by the archive being corrupted in some way (manual tar extraction fails too). Can you try to re-export the tar archive as shown in the tutorial? 
Also, related, your submission looks suspiciously small. Usually for the whole validation set, we see submissions of sizes around 30GB. Are you including all the validation scenarios?
