### ISSUE TITLE
Future traffic light states in test dataset for Sim Agent Challenge

### ISSUE THREAD

**Issue by yougeyxt** [waymo-research/waymo-open-dataset#662]
Hi,

It seems that the test dataset only contains traffic light states for the input duration of 1 second, and does not include traffic light states for future time intervals. For the Sim Agent Challenge, does that mean we also need to simulate (generate) the traffic light states on our own?

Thank you in advance for clarifying that.

Best,
Xintao

**Comment by nicomon24** [comment]
Hi @yougeyxt, yes you are correct, the test set does not include future traffic light states.
In theory yes, by simulating traffic light states realistically, you should be able to generate a better scoring submission. 
From our exploratory experiments the difference shouldn't be massive, as these are 8s-long simulations, and usually traffic lights have a longer durations, and we don't see traffic light changes as frequently in Scenarios. 
Happy to hear your thoughts on this too,

Nico

**Comment by nicomon24** [comment]
Hi @yougeyxt, 
In principle a simulator should also simulate information about traffic lights, as this are still "unknown" latent variables to the AV itself. Being exogenous depends on where you place the border between "what is simulated" and "what is externallu defined". In this case, we are making as few assumptions as possible, so the task here is quite similar to developing a "world model" instead of just a "traffic simulator".
This is an arbitrary choice we made, so I understand that other solutions might be also valid.
I'd be happy to discuss more if you want, we are trying to address all these little details in the proceedings of this challenge, so feedback is always appreciated!

Add: we are having office hours tomorrow and friday if you need direct feedback (see pinned post).
