### ISSUE TITLE
Sim Agents: the compute of likelihood about the features in validation

### ISSUE THREAD

**Issue by QC625** [waymo-research/waymo-open-dataset#671]
For the validation, the result is not 1 when I try to submit the ground truth to compute the likelihood. Is there anything wrong?

**Comment by nicomon24** [comment]
Hi @QC625
If you are referring to the meta-metric value, since we are using a metric config with flag `independent_timesteps: true`, the likelihood computation will not be exactly 1 even by replaying the ground truth. If you look at the documentation in the metric code it should be clear why this is the case, otherwise let me know if you need further clarifications.

Just to double-check, when using the ground truth directly, are you seeing the ADE metrics to be roughly zero? If this is the case, then it's not an issue (it's just the intended scaling I was mentioning above), if it's not, you might actually have some errors / bugs somewhere in your code.

Hope this helps!
Nico

**Comment by nicomon24** [comment]
Hi @QC625, thanks a lot for the additional info!

Given that the ADE is zero, then yes, you are doing things correctly. As I was saying, values for the likelihoods metrics are not 1 because when `independent_timesteps: true`, we are taking **all** the values for the feature, say speed, over the whole 8s of simulation. Each log sample is then scored against this aggregated distribution of 32(samples) * 80 (steps), which means that the ground-truth  likelihood will not be 1. We have baseline experiments for validation and test, so there a theoretical limit to the likelihood metrics (less than 1). 

For the validity issue, again, everything should be clear from the code documentation, but I'll try to recap here:
for every step (and for every object) we are computing the likelihood of the log sample against the simulated distribution. This will not happen for invalid objects, because we have no ground truth to score. But since we are not releasing any validity information (for the future) for the test set, submissions should assume the object to "continue" to be valid, and provide reasonable simulations anyway. If the object turns out to be invalid, these will not be used for scoring. 

I also wanted to mention that we are going to have office hours tomorrow and on friday if you have further questions (see pinned post). Hope this helps!

**Comment by QC625** [comment]
OK, thanks!
