### ISSUE TITLE
The calculation method for the evaluation metrics of the Sim agent competition

### ISSUE THREAD

**Issue by Guozhiming-art** [waymo-research/waymo-open-dataset#701]
Dear Waymo team,

I found that there seem be some problems in the metric calculation in the Sim Agent Task. Specifically, the valid mask is set to True for all the future trajectory of the ground truth in the computation of the Collision indication and Offroad indication. However,  the actual validity of some cars are False at several future time, padded with x=0, y=0, z=0. This unavailable positions will additionally lead to out of bounds (and collisions) of the ground truth and thereby incorrect GT distribution.

![图片](https://github.com/waymo-research/waymo-open-dataset/assets/76396377/a3bf4326-aef2-499b-86d5-6e14b4c6b44b)
![图片](https://github.com/waymo-research/waymo-open-dataset/assets/76396377/a8362de9-730f-45a3-abb8-c7df59830eb0)

In contrast, I noticed that the future trajectory of the ground truth are correctly used for computing the kinematic similarity with use_log_valid. However, when calculating the Collision indication and Offroad indication metrics, the results are directly averaged  without considering the validity of the ground truth in the code：
![图片](https://github.com/waymo-research/waymo-open-dataset/assets/76396377/d86a43a7-05eb-4507-afd0-7e302f73f127)

I would appreciate if you could check the correctness of the calculation of the Collision indication and Offroad indication, especially at the testing phase.
Thanks. 
Best,
@nicomon24

**Comment by nicomon24** [comment]
Hi @Guozhiming-art,

First, let me try to explain what is the rationale behind the logic here, and if you still think there is a bug we can look into that. 

## Log-validity vs. sim-validity
As you might have noticed, in the real world, we objects appearing and disappearing, which is tracked by the validity flag. While, to perfectly "mimic" the data in the open dataset you would have to also correctly model this appearing/disappearing, we thought that it would have made the problem even harder and a bit less tractable.
Our strategy here is to ask **simulations** to be fully valid, but only evaluate the part that is actually valid in the data (because, at that point, you don't have data to say what happened next). 
So, it is intended that, while computing **log** features, we are using the validity mask and not using when doing sim.

## Collisions and offroad on log
If you following the code from trajectories to the actual collision score, you can find the following steps:
1. Compute distances between objects. If an object is invalid, a distance of `_EXTREMELY_LARGE_DISTANCE` will be assigned. This is what happens when in the "log", an object is invalid (and this should filter out the first thing you said, i.e. colliding when they are put to x=0,y=0,z=0).
2. Compute collisions if the distance is lower than a threshold. When invalid, this threshold should never be reached.

The same logic should apply to offroad, but with `-_EXTREMELY_LARGE_DISTANCE` and a `>=` to flag offroad events.

## Collision and offroad scores
Using a fully-valid mask on the simulated states is instead somewhat of an arbitrary choice. First, notice how the collision and offroad events from the previous steps are already not a timeseries anymore, so it's just one value to say "was the any collision (offroad) in the whole run for that object?"
So, by not filtering by the original validity mask, but a full-valid mask, we are basically saying "was there any collision **ever** in the simulated run?" instead of "was there a collision **before the invalid part of the original run** in the simulated run?"
This was arbitrary and intended for the evaluation.

I hope this explains the evaluation story better, if not please let me know, I'm happy to help and debug things.

Nico

**Comment by Guozhiming-art** [comment]
Hi @nicomon24
I understand the process you said, and the calculation process in the code also confirms that. I noticed that you use the boolean value "use_log_validity" to distinguish between the "log" and "simulated" states.
![图片](https://github.com/waymo-research/waymo-open-dataset/assets/76396377/3247369a-d959-4889-925c-e8f03ecf9856)
However, the variable “validity_mask” is not used in the subsequent calculation of the out-of-bounds or collision distance：
![图片](https://github.com/waymo-research/waymo-open-dataset/assets/76396377/f1aafdc1-39ec-4ecb-8bc2-b3c76f84d8d5)
However, whether for the "log" or "simulated" states, the variable "simulated_trajectories.valid" is True for the next 80 frames:
![图片](https://github.com/waymo-research/waymo-open-dataset/assets/76396377/9acfff3e-5026-4ca4-91fa-a60a3c39057e)
![图片](https://github.com/waymo-research/waymo-open-dataset/assets/76396377/9c85ccdb-fc19-4219-a111-18b1f463c5de)
This is inconsistent with the actual valid status of the “log” trajectory.
You can check the scenario with scenario_id=f3423644c33320eb, which appears specifically in the file “uncompressed_scenario_validation_validation.tfrecord-00000-of-00150”. In this scenario, all cars are driving straight and there are no cases of going out of bounds. However, when calculating the “is_offroad” index of the "log" trajectory, due to the problem of “simulated_trajectories.valid”, some cars are mistakenly identified as going out of bounds.
I would appreciate if you could check this case.
Thanks.
Best,

**Comment by nicomon24** [comment]
Hi @Guozhiming-art,

Thanks, now I understand where the problem is. Let me do some debugging and tests and get back to you.
Thanks for spotting this! 

Nico

**Comment by Guozhiming-art** [comment]
Hi @nicomon24
Thanks your for your help

**Comment by Guozhiming-art** [comment]
Hi @nicomon24
Since I submitted the test file yesterday, it has been 24 hours and it is still displaying "This submission could not be found. If it was recently uploaded, it may still be processing. Check back in about 6 hours. Please avoid resubmitting if a submission is still processing, as it might overload the server." Could you please check if it is congested on the server side like last time? My email account for participating in the competition is hu15645090213@gmail.com.
Thanks.
Best,

**Comment by nicomon24** [comment]
Hi @Guozhiming-art,
Sorry for taking a bit of time. On the main issue, I can confirm there is a bug on the collision/offroad. This might affect the past evaluations for submissions so we are proceeding carefully with the next steps, so this might take a longer time (we also have a few people OOO :)).

Re. the last evaluation you submitted: yes you are indeed right, I think the auto-scaling of the server was too conservative after the challenge ended and we were seeing a lot less submissions. Let me fix that and get back to you once the evaluation is completed

**Comment by Guozhiming-art** [comment]
Hi @nicomon24
Thanks your for your help
