### ISSUE TITLE
Distorded or undistorded images - Waymo-open-dataset v2

### ISSUE THREAD

**Issue by JulienStanguennec-Leddartech** [waymo-research/waymo-open-dataset#834]
Hi,

Thanks for this very cool dataset and API provided. Using the v2 API with parquet files for 3d-gaussian-splatting and nerf research with nerfstudio.

This is a question that was asked many times, and mainly answered that the images are distorted: 
- https://github.com/waymo-research/waymo-open-dataset/issues/53
- https://github.com/waymo-research/waymo-open-dataset/issues/53#issuecomment-546151674
- https://github.com/waymo-research/waymo-open-dataset/issues/24
- https://github.com/waymo-research/waymo-open-dataset/issues/24#issuecomment-535794541
- https://github.com/waymo-research/waymo-open-dataset/issues/66

But this message make me doubtful:
- https://github.com/waymo-research/waymo-open-dataset/issues/192#issuecomment-638558257
> For 5, TFRecords stores the **undistorted image** is for resolving the rolling shutter problem. The pre-distorted image cannot be used to resolve the rolling shutter problem latter.

**Question:** Could you confirm that images read out of parquet file using v2 api distorted or undistorted ?

To get undistorted images, doing the following should be reasonable enough ?
```{python}
newK, roi = cv2.getOptimalNewCameraMatrix(K, distortion_params, (image.shape[1], image.shape[0]), 0)
image = cv2.undistort(image, K, distortion_params, None, newK)  # type: ignore
```

Plotting 8 corner of the box points:
- In blue projection with `py_camera_model_ops.world_to_image` function from `from waymo_open_dataset.wdl_limited.camera.ops import py_camera_model_ops`
- In green cv2 projection with null distortion parameters with  `cv2.projectPoints(boxes_pts_camera_ref,np.zeros((3,)),np.zeros((3,)),intrinsic,np.zeros((5,1)))`
- In yellow cv2 projection with actual distortion parameters from calibration in waymo. `cv2.projectPoints(boxes_pts_camera_ref,np.zeros((3,)),np.zeros((3,)),intrinsic,np.array([intrinsic_dict['k1'],intrinsic_dict['k2'],intrinsic_dict['p1'],intrinsic_dict['p2'],intrinsic_dict['k3']]), #np.zeros((5,1)),`
![image](https://github.com/waymo-research/waymo-open-dataset/assets/44166203/fffe5083-ab8f-400a-9b49-4a410c64789c)

It seems that the images are distorted, and that cv2 projectPoints has a hard time with object out of the fov...
From https://github.com/waymo-research/waymo-open-dataset/blob/master/src/waymo_open_dataset/wdl_limited/camera/camera_model.h, it does seem to show that images are distorted:
![image](https://github.com/waymo-research/waymo-open-dataset/assets/44166203/84486690-bd73-408c-bdb1-296871c3fe59)

Nonetheless, could we get a confirmation of this ?

Thanks a lot

**Comment by VincentCa** [comment]
Hi Julien,

Thanks for your interest in Waymo Open Dataset! I think this confusion stems from the fact that people are referring to different things here - namely lens distortion vs. rolling shutter distortion.

All images in the dataset are **lens distorted** and we provide camera parameters to optionally undistort them if you prefer (you don't have to for most use-cases - our camera model accurately projects either way if initialized correctly). In practice, naturally the effects of lens distortion will be most noticeable near the image boundaries, but overall the distortion effect is not very strong, so it looks like something else went wrong with your code that generated the yellow box. At first glance, we only provide k1 and k2 distortion coefficients, and k3 through k5 should be zero, but you are setting them to some other variable - I would suggest to double check this part.

All images are also affected by **rolling shutter distortion**, which is something that can not easily be undone on an image-level, since the distortion effects have complex dependencies, including the distance of the pixel, the camera velocity etc. However, our camera model natively handles and solves for rolling shutter distortion as well if initialized correctly. To better align 3D labels and the camera imagery in the presence of fast egomotion, we have released camera-synchronized box labels that you can use also. You can have a look at our tutorial for more information: https://github.com/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial_camera_only.ipynb

Hope this helps!
Vincent, on behalf of the Waymo Open Dataset team

**Comment by JulienStanguennec-Leddartech** [comment]
That's clear. Thanks.
