### ISSUE TITLE
Missing `uses_lidar_data` field from submission.

### ISSUE THREAD

**Issue by MPCheng-ZW** [waymo-research/waymo-open-dataset#881]
Thank you for your excellent work!

When I submitted the validation results, I encountered the error: "Missing uses_lidar_data field from submission."

Do you know how I can resolve this issue?

Additionally, I am using a small training/validation/test set with only around twenty samples for convenience.

**Comment by jlambert-waymo** [comment]
Hi @MPCheng-ZW, you need to indicate in your submission proto whether or not you used LiDAR data for model training / inference.

The motion and sim agent submission protos have the following field: `optional bool uses_lidar_data = 9;`

https://github.com/waymo-research/waymo-open-dataset/blob/5f8a1cd42491210e7de629b6f8fc09b65e0cbe99/src/waymo_open_dataset/protos/motion_submission.proto#L158

https://github.com/waymo-research/waymo-open-dataset/blob/5f8a1cd42491210e7de629b6f8fc09b65e0cbe99/src/waymo_open_dataset/protos/sim_agents_submission.proto#L98

Which challenge are you submitting to? You'll need to submit results for the entire dataset split you are submitting for, in order to get a valid result back from the server. We discuss this under the April 2024 Update in the [README](https://github.com/waymo-research/waymo-open-dataset?tab=readme-ov-file#april-2024-update).

**Comment by MPCheng-ZW** [comment]
Thank you for your reply!

I am submitting the results for the Occupancy and Flow Prediction challenge.

I understand that the results should be submitted based on the entire dataset. At this stage, I am only using the small dataset to debug the code. Will the inference results from the small dataset be displayed successfully?

Also, which version of waymo-open-dataset-tf should I install via pip?

Lastly, how can I indicate whether or not LIDAR data is being used?

Thank you very much!

@jlambert-waymo
